import Nav from '@/component/navbar/Nav'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import 'react-notifications/lib/notifications.css';
import Contextapi from './contextapi';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning >

        <Contextapi >
          <Nav />
          {children}
        </Contextapi>
      </body>
    </html>
  )
}
